# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
  - init: cd qr-code-generator && wasm-pack build # runs during prebuild
  - init: yarn

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
