# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, test-branches ]
  pull_request:
    branches: [ master, test-branches ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - run: cargo test
        name: Launch Rust tests
        working-directory: ./qr-code-generator
      - run: wasm-pack test --headless --chrome
        working-directory: ./qr-code-generator
      - run: wasm-pack test --headless --firefox
        working-directory: ./qr-code-generator
      - run: wasm-pack build
        working-directory: ./qr-code-generator

      - uses: actions/setup-node@v2
      - run: yarn
      - run: yarn build
      - name: Deploy to production
        uses: awb-pw/deploy-to-github-pages-action@1.1.1
        env:
          AUTHOR: bachrc
          BUILD_PATH: build
          GITHUB_PAGE_NAME: bachrc.github.io
          PA_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
          USERNAME: bachrc
          EMAIL: bachrc@dessert.coffee
